project_id = "lwjtuzysxajewugkctny"

[functions.stock-market]
verify_jwt = false

[functions.gold-prices]
verify_jwt = false

[functions.latest-news]
verify_jwt = false

[functions.politics]
verify_jwt = false

[functions.hybrid-chat]
verify_jwt = false

[functions.rag-chat]
verify_jwt = false